;==================================================================================================

#NoEnv

SetBatchLines -1
SetTitleMatchMode 2
#SingleInstance Force
#NoTrayIcon

;by: jakiś ziomek z reddita
;kot poprawił i dodał coś od siebie

;===================================================================================================
;GUI
;===================================================================================================

; Generated by AutoGUI 1.4.9a
; Naprawione przez k0
#NoEnv
#SingleInstance Force
SetWorkingDir %A_ScriptDir%

Gui Font, s17 Bold q5, Palatino Linotype
Gui Add, Text, x28 y8 w107 h23 +0x200, MakroKit
Gui Font
Gui Font, s9 Italic
Gui Add, Text, x66 y32 w32 h23 +0x200, by k0
Gui Font
Gui Add, Button, x8 y64 w80 h23 gFishing, % "Łowienie (ppm)"
Gui Add, Button, x88 y64 w80 h23 gDig, % "Kopanie (lpm)"
Gui Add, Button, x8 y88 w158 h23 gAttack, % "Szerokie ostrze (1s lpm)"
Gui Add, Text, x8 y128 w158 h23 +0x200, Wpisz ilość CPS dla autoklikera
Gui Add, Edit, x8 y152 w158 h21 vCPS
Gui Add, Button, x8 y176 w80 h23 gSpamlpm, % "LPM"
Gui Add, Button, x88 y176 w80 h23 gSpamppm, % "PPM"
Gui Add, Button, x8 y208 w158 h40 gStop, % "Zatrzymaj wszystkie makra"

Gui Show, w175 h254, MakroKit
WinSet, Transparent, 170, MakroKit
Return

GuiEscape:
GuiClose:
    ExitApp

	
	

	

;===================================================================================================
;===================================================================================================
Fishing:
{
IfWinExist ("Minecraft 1. ahk_exe javaw.exe")
	BreakLoop = 0
ControlClick, , Minecraft 1. ahk_exe javaw.exe, ,Right, , NAD
		Loop
		{
			if (BreakLoop = 1)
			{
				Sleep 500
				ControlClick, , Minecraft 1. ahk_exe javaw.exe, ,Right, , NAU
				BreakLoop = 0
				break
			}
		}
	Return
}
Dig:
{
IfWinExist ("Minecraft 1. ahk_exe javaw.exe")
	BreakLoop = 0
ControlClick, , Minecraft 1. ahk_exe javaw.exe, ,Left, , NAD
		Loop
		{
			if (BreakLoop = 1)
			{
				Sleep 500
				ControlClick, , Minecraft 1. ahk_exe javaw.exe, ,Left, , NAU
				BreakLoop = 0
				break
			}
		}
	Return
}
Attack:
{
IfWinExist ("Minecraft 1. ahk_exe javaw.exe")
	BreakLoop = 0
		Loop
		{
			if (BreakLoop = 1)
			{
				BreakLoop = 0
				break
			}

			Sleep 1250
				ControlClick, , Minecraft 1. ahk_exe javaw.exe, ,Left, , NA
		}
	Return
}

Spamlpm:
{
Gui, Submit, NoHide
IfWinExist ("Minecraft 1. ahk_exe javaw.exe")
	BreakLoop = 0
		Loop
		{
			if (BreakLoop = 1)
			{
				BreakLoop = 0
				break
			}

			Sleep 1000 / CPS
				ControlClick, , Minecraft 1. ahk_exe javaw.exe, ,Left, , NA
		}
	Return
}

Spamppm:
{
Gui, Submit, NoHide
IfWinExist ("Minecraft 1. ahk_exe javaw.exe")
	BreakLoop = 0
		Loop
		{
			if (BreakLoop = 1)
			{
				BreakLoop = 0
				break
			}

			Sleep 1000 / CPS
				ControlClick, , Minecraft 1. ahk_exe javaw.exe, ,Right, , NA
		}
	Return
}
;==================================================================================================
Stop:
BreakLoop = 1
return

;===================================================================================================
